### PR TITLE
Add blog post for kcp at KubeCon EU 2024

### PR DESCRIPTION
**Pull request by embik**
This adds a blog post for our KubeCon + CloudNativeCon EU presence, listing all the sessions that maintainers are hosting this year.

Also slightly updates the stylesheet so that links are properly colored.

### CODE REVIEW

**Comment by embik** [comment]
/hold

This can now be reviewed, but should not be merged before Wednesday (due to the release date on the post).

**Comment by mjudeikis** [comment]
/lgtm
/approve
/hold

lets wait for other reviews but looks good!

**Pull request merged**
