### PR TITLE
Add a blog post for KubeCon NA 2024 in SLC

### PR DESCRIPTION
**Pull request by embik**
This adds a small blog post for what to see at KubeCon + CloudNativeCon NA 2024 in regards to kcp.

### CODE REVIEW

**Comment by embik** [comment]
(I can also add someone else as author [in addition?] so my face isn't the only one on all those posts on the blog, feel free to volunteer yourself :D)

**Comment by embik** [comment]
/hold

until publishing date of the post.

**Comment by sttts** [comment]
Looks great!

**Pull request merged**
